/**
 * Session Compacting Hook — inject build context on compaction
 * 
 * CRITICAL: Only fires for shark agents.
 * AUTO-INJECT: Writes context file for next session to read.
 * 
 * Context file location: .shark/build-context.md
 */

import type { Hooks } from '@opencode-ai/plugin';
import { GateManager } from '../../shared/gates.js';
import { isSharkAgent } from '../../shared/agent-identity';
import * as fs from 'node:fs';
import * as path from 'node:path';

const BUILD_CONTEXT_FILE = 'build-context.md';

const BUILD_CONTEXT = `
# SHARK AGENT v4.8.3 BUILD CONTEXT

## STATUS: NOT SHIP READY

### What's Working
- L5 Message Blocking: 11/11 tests PASS
- Pattern Counts: 15/15 arrays verified (156 total patterns)
- Build: 0.60 MB bundle, 102 modules
- Memory: No nested agents

### What's Broken
- L1-L4 Tool-Level Blocking: getCurrentAgent() returns undefined
- Root cause: guardian-hook.ts:469-471 early return bypasses all checks

## THE BUG

In \`src/hooks/v4.1/guardian-hook.ts:469-471\`:
\`\`\`typescript
if (!getCurrentAgent()) {
  return;  // ← ALL L1-L4 checks bypassed
}
\`\`\`

The \`getCurrentAgent()\` returns undefined even though chat.message already called \`setCurrentAgent('shark')\`.

## ARCHITECTURE

User Input → chat.message (L5 blocks here ✅) → Agent → tool.execute.before (L1-L4 broken ❌) → Tool

## FIX OPTIONS

### Option 1: Debug (Quick)
Add console.log at guardian-hook.ts:469 to trace state.

### Option 2: Session-based state
Use session ID map instead of module-level variable.

### Option 3: Remove early return
Always check dangerous tools, only skip L1-L4 for non-dangerous when no agent.

## TESTING

### Container Setup
\`\`\`bash
docker run --rm -d -v /tmp/shark-container/config:/root/.config/opencode -v /tmp/shark-container/plugins:/root/.config/opencode/plugins --entrypoint /bin/sh opencode-test:1.4.3 -c "tail -f /dev/null"
\`\`\`

### Test L5 (Working)
\`\`\`bash
echo "skip container test" | timeout 120 docker exec -i CONTAINER /usr/local/lib/node_modules/opencode-ai/node_modules/opencode-linux-x64/bin/opencode --agent shark --model opencode/big-pickle 2>&1 | grep 'ANTI-DERAILMENT'
# Expected: BLOCKED with L5.1 error
\`\`\`

### Test L1 (Broken)
\`\`\`bash
echo "run grep pattern | wc -l" | timeout 120 docker exec -i CONTAINER /usr/local/lib/node_modules/opencode-ai/node_modules/opencode-linux-x64/bin/opencode --agent shark --model opencode/big-pickle 2>&1 | grep 'ANTI-SLOP'
# Current: NO BLOCK (broken)
# After fix: BLOCKED with L1 error
\`\`\`

## KEY FILES

- \`src/hooks/v4.1/guardian-hook.ts\` - L1-L4 broken here (line 469)
- \`src/hooks/v4.1/chat-message-hook.ts\` - L5 working here
- \`src/hooks/v4.1/agent-state.ts\` - getCurrentAgent() source

## PATTERNS

L5 Anti-Derailment (Working): L5.1-L5.10 (143 patterns across 10 sub-layers)
- L5.1: Host fallback (skip container test)
- L5.2: Success claim (it works trust me)
- L5.3: Model restriction (must use gpt)
- L5.4: Mock/stub (use mock data)
- L5.5: Simplification (hand wave)
- L5.6: Confusion pretense (it somewhat works)
- L5.7: Cross-agent tools (hermes_, hive_, kraken_, mem_, knowledge_)
- L5.8: Undermining (not worth the effort)
- L5.9: Impatience (let's just ship it)
- L5.10: Self-reference (I verified it works)

L1-L4 Tool Patterns (Broken): L1-L4 (not blocking)

## BUILD COMMANDS

\`\`\`bash
cd /home/leviathan/OPENCODE_WORKSPACE/projects/shark-agent-v4
bun build src/index.ts --outdir dist --target bun --format esm --bundle --external @opencode-ai/plugin
bun run test-patterns.ts  # Verify 15/15 arrays
\`\`\`

## SUCCESS CRITERIA

- [ ] L1 blocks theatrical commands (grep | wc)
- [ ] L2 blocks fake test runners (npm test, jest)
- [ ] L5 still blocks behavioral derailment
- [ ] 15/15 pattern arrays verified
- [ ] Build succeeds (0.60 MB)

---

Generated by compacting-hook.ts on compaction.
`.trim();

export function createCompactingHook(
  gateManager: GateManager
): Hooks['experimental.session.compacting'] {
  return async (input) => {
    const { agent } = input;
    
    if (!isSharkAgent(agent)) return;
    
    // Write build context file for next session to read
    try {
      const sharkDir = path.join(process.cwd(), '.shark');
      const autoInjectDir = path.join(sharkDir, 'auto-inject');
      
      // Ensure directories exist
      if (!fs.existsSync(sharkDir)) {
        fs.mkdirSync(sharkDir, { recursive: true });
      }
      if (!fs.existsSync(autoInjectDir)) {
        fs.mkdirSync(autoInjectDir, { recursive: true });
      }
      
      // Write to PRIMARY location (for manual copy/paste reinject)
      const primaryPath = path.join(autoInjectDir, 'BUILD_CONTEXT.md');
      fs.writeFileSync(primaryPath, BUILD_CONTEXT, 'utf-8');
      
      // Write legacy location (for auto-inject system)
      const legacyPath = path.join(sharkDir, BUILD_CONTEXT_FILE);
      fs.writeFileSync(legacyPath, BUILD_CONTEXT, 'utf-8');
      
      // Also write a compact "reminder" for faster loading
      const reminderPath = path.join(sharkDir, 'build-reminder.txt');
      fs.writeFileSync(reminderPath, `L1-L4 BROKEN: guardian-hook.ts:469 getCurrentAgent() returns undefined. L5 working. Fix: src/hooks/v4.1/agent-state.ts`, 'utf-8');
      
    } catch (err) {
      // Silent fail - don't disrupt compaction
    }
  };
}